import { getBonusRequestForReview } from "../../../lib/approval_workflow.js";
import { listBonusAuditors } from "../../../lib/auditors.js";
import ReviewClient from "./ReviewClient.js";
import FinalApprovalClient from "./FinalApprovalClient.js";
import PriceReviewClient from "./PriceReviewClient.js";
import styles from "./review.module.css";

export const dynamic = "force-dynamic";

const FIELD_MAP = {
  FC: [["folio_factura_compra", "Folio factura compra"], ["fecha_factura_compra", "Fecha factura compra"], ["precio_compra_total", "Total factura compra"], ["nota_venta", "Nota de venta"], ["vin", "VIN"]],
  FV: [["folio_factura_venta", "Folio factura venta"], ["fecha_factura_venta", "Fecha factura venta"], ["precio_venta_total", "Total factura venta"], ["nombre_facturado", "Facturado a"], ["rut_facturado", "RUT facturado"], ["nombre_compra_para", "Compra para"], ["rut_compra_para", "RUT compra para"], ["vin", "VIN"]],
  INSCRIPCION: [["vin", "VIN inscripción"], ["nombre_adquirente", "Adquirente"], ["rut_adquirente", "RUT adquirente"], ["ppu", "PPU"], ["marca", "Marca"], ["modelo", "Modelo"]],
  FINANCIAMIENTO: [["nombre_cliente", "Cliente"], ["rut_cliente", "RUT cliente"], ["financiera", "Financiera"], ["monto_financiado", "Monto financiado"], ["numero_operacion", "Número operación"]],
  REPOSICION: [["vin_original", "VIN operación"], ["vin_nuevo", "VIN reposición"], ["fecha", "Fecha reposición"], ["monto_total", "Monto reposición"]],
};
const AUDIT_LABELS={
  REQUIERE_REVISION_HUMANA:"Requiere revisión humana",
  CALCULATION_REQUIRES_REVIEW:"El cálculo requiere revisión",
  PDV_PENDING:"Falta validar la cuadratura del precio de venta",
  TOTAL_DEVOLVER_PENDING:"Falta calcular el total a devolver",
  FECHA_VENTA_REQUIRED:"Falta la fecha de venta",
  PRICE_LOOKUP_NOT_FOUND:"No se encontró precio aplicable",
  PRICE_LOOKUP_AMBIGUOUS:"Hay más de una versión de precio posible",
};
function humanAudit(value){const key=String(value||"").trim().toUpperCase();return AUDIT_LABELS[key]||String(value||"").replaceAll("_"," ").toLowerCase().replace(/^./,(c)=>c.toUpperCase());}
function asList(value){if(Array.isArray(value))return value.filter(Boolean);if(!value)return[];try{const parsed=typeof value==="string"?JSON.parse(value):value;return Array.isArray(parsed)?parsed.filter(Boolean):[];}catch{return[];}}
function money(value){if(value===null||value===undefined||value==="")return"-";const number=Number(value);return Number.isFinite(number)?`$ ${Math.trunc(number).toLocaleString("es-CL")}`:"-";}
function extractionOf(document){return document?.reviewed_extraction||document?.extraction||{};}
function normText(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]+/g," ").trim().replace(/\s+/g," ");}
function normRut(value){return String(value||"").toUpperCase().replace(/[^0-9K]/g,"");}
function comparable(value,kind){return kind==="rut"?normRut(value):normText(value);}
function makeCheck(value,references,kind){const current=comparable(value,kind);const refs=references.filter((x)=>x?.value).map((x)=>({...x,normalized:comparable(x.value,kind)})).filter((x)=>x.normalized);if(!current||!refs.length)return null;const matched=refs.filter((x)=>x.normalized===current);const ok=matched.length===refs.length;const matchedLabels=matched.map((x)=>x.label);const missingLabels=refs.filter((x)=>x.normalized!==current).map((x)=>x.label);return {ok,label:ok?`Coincide con ${refs.map((x)=>x.label).join(" e ")}`:`No coincide con ${missingLabels.join(" ni ")}`,detail:matchedLabels.length?`Coincide con ${matchedLabels.join(" y ")}; revisar ${missingLabels.join(" y ")}.`:`No coincide con ${refs.map((x)=>x.label).join(" ni ")}.`};}
function buildCrossChecks(documents,current){const byType=new Map(documents.map((doc)=>[doc.document_type,extractionOf(doc)]));const fv=byType.get("FV")||{};const ins=byType.get("INSCRIPCION")||{};const currentData=extractionOf(current);const fvName=fv.nombre_compra_para||fv.nombre_facturado;const fvRut=fv.rut_compra_para||fv.rut_facturado;if(current?.document_type==="INSCRIPCION")return {nombre_adquirente:makeCheck(currentData.nombre_adquirente,[{label:"venta",value:fvName}],"text"),rut_adquirente:makeCheck(currentData.rut_adquirente,[{label:"venta",value:fvRut}],"rut")};if(current?.document_type==="FINANCIAMIENTO")return {nombre_cliente:makeCheck(currentData.nombre_cliente,[{label:"venta",value:fvName},{label:"inscripción",value:ins.nombre_adquirente}],"text"),rut_cliente:makeCheck(currentData.rut_cliente,[{label:"venta",value:fvRut},{label:"inscripción",value:ins.rut_adquirente}],"rut")};return {};}
function AuditSummary({request}){const cierre=String(request.cierre_estado||"").toUpperCase();const inconsistencias=asList(request.inconsistencias);const tone=cierre==="ROJO"?styles.auditRed:request.requiere_revision_humana||cierre==="AMARILLO"?styles.auditYellow:styles.auditGreen;return <section className={`${styles.auditSummary} ${tone}`}><div className={styles.auditHeadline}><div><small>Resultado auditor automático</small><strong>{cierre||"SIN CIERRE"}</strong></div><span>{humanAudit(request.audit_status)||"Sin estado"}</span></div><div className={styles.auditBody}><div><small>Documentación</small><strong>{request.documentacion_estado||"-"}</strong></div><div><small>Revisión humana</small><strong>{request.requiere_revision_humana?"Requerida":"No requerida"}</strong></div><div className={styles.auditObservations}><small>Observaciones activas</small>{inconsistencias.length?<ul>{inconsistencias.map((item)=><li key={item}>{humanAudit(item)}</li>)}</ul>:<strong>Sin observaciones</strong>}</div></div></section>;}
function InventoryFcSummary({evidence}){if(!evidence?.fc_reconstruida)return null;return <section className={styles.inventoryFc}><div className={styles.inventoryFcHeader}><div><small>Factura de compra</small><strong>FC reconstruida desde inventario</strong></div><span>INFORMATIVO</span></div><p>Factura de compra no aportada por dealer. Datos reconstruidos desde inventario interno CIDEF por VIN.</p><div className={styles.inventoryFcGrid}><div><small>Factura</small><strong>{evidence.folio_factura_compra||"-"}</strong></div><div><small>Fecha</small><strong>{evidence.fecha_factura_compra||"-"}</strong></div><div><small>Monto</small><strong>{money(evidence.precio_compra_total)}</strong></div><div><small>Dealer</small><strong>{evidence.dealer||"-"}</strong></div><div><small>Marca / modelo</small><strong>{[evidence.marca,evidence.modelo].filter(Boolean).join(" · ")||"-"}</strong></div><div><small>Fuente</small><strong>{evidence.source_table||"inventario_vehiculos_global_raw"}</strong></div></div></section>;}
function ConsolidatedSummary({review,auditors}){const request=review.request;const priceHref=`/admin-v2/request?id=${encodeURIComponent(request.id)}&stage=prices`;return <section className={styles.consolidated}><div className={styles.priceHeader}><div><small>Consolidado final</small><strong>Solicitud completa para aprobación</strong></div><span>{request.pdv_ok||"PRECIO DE VENTA SIN VALIDAR"}</span></div><div className={styles.consolidatedIdentity}><div><small>VIN</small><strong>{request.vin||"-"}</strong></div><div><small>Dealer</small><strong>{request.dealer_nombre||"-"}</strong></div><div><small>Estado</small><strong>{request.estado||"-"}</strong></div><div><small>Total devolución</small><strong>{money(request.total_devolver)}</strong></div></div><div className={styles.consolidatedSection}><h2>Documentos validados</h2><div className={styles.documentCards}>{review.documents.map((document)=><a key={document.document_type} href={`/admin-v2/request?id=${encodeURIComponent(request.id)}&doc=${encodeURIComponent(document.document_type)}`}><small>{document.document_type}</small><strong>{document.review_status||"PENDIENTE"}</strong></a>)}</div></div><div className={styles.consolidatedSection}><div className={styles.sectionHeading}><h2>Precio y bonos</h2><a href={priceHref}>← Volver a validar precios</a></div><div className={styles.priceGrid}><div><small>Lista utilizada</small><strong>{request.lista_precio_utilizada||"-"}</strong></div><div><small>Precio lista venta</small><strong>{money(request.precio_lista_venta)}</strong></div><div><small>Bono CIDEF</small><strong>{money(request.bono_cidef)}</strong></div><div><small>Bono cierre</small><strong>{money(request.bono_cierre)}</strong></div><div><small>Bono financiamiento</small><strong>{money(request.bono_fin)}</strong></div><div><small>Diferencia precio</small><strong>{money(request.bono_dif)}</strong></div><div><small>Descuento dealer</small><strong>{money(request.descuentos_dealer)}</strong></div><div><small>Validación precio de venta</small><strong>{request.pdv_ok||"-"}</strong></div><div className={styles.priceTotal}><small>Total devolución</small><strong>{money(request.total_devolver)}</strong></div></div></div><FinalApprovalClient requestId={request.id} auditors={auditors}/></section>;}

export default async function RequestReviewPage({searchParams}){
  const params=await searchParams;const id=String(params?.id||"").trim();const requestedDoc=String(params?.doc||"").trim().toUpperCase();const stage=String(params?.stage||"prices").trim().toLowerCase();
  const [review,auditors]=await Promise.all([id?getBonusRequestForReview(id):null,listBonusAuditors()]);
  if(!review)return <main className={styles.screen}><a className={styles.back} href="/admin-v2">← Volver</a><p>Solicitud no encontrada.</p></main>;
  const sequenceDocs=review.sequence.map((type)=>review.documents.find((x)=>x.document_type===type)).filter(Boolean);const defaultType=sequenceDocs[0]?.document_type||"";const selectedType=sequenceDocs.some((x)=>x.document_type===requestedDoc)?requestedDoc:defaultType;const current=sequenceDocs.find((x)=>x.document_type===selectedType)||null;const currentIndex=current?sequenceDocs.findIndex((x)=>x.document_type===current.document_type):-1;const step=currentIndex>=0?currentIndex+1:sequenceDocs.length;const previousType=currentIndex>0?sequenceDocs[currentIndex-1].document_type:null;const nextType=currentIndex>=0&&currentIndex<sequenceDocs.length-1?sequenceDocs[currentIndex+1].document_type:null;const dealerLabel=review.request.dealer_nombre||"Dealer no identificado";const reviewingApprovedDocument=Boolean(review.review_complete&&requestedDoc&&current);const firstDocumentHref=defaultType?`/admin-v2/request?id=${encodeURIComponent(review.request.id)}&doc=${encodeURIComponent(defaultType)}`:null;const crossChecks=buildCrossChecks(review.documents,current);
  let content=null;if(current&&(!review.review_complete||reviewingApprovedDocument)){content=<ReviewClient requestId={review.request.id} document={current} fields={FIELD_MAP[current.document_type]||[]} step={step} total={sequenceDocs.length} previousType={previousType} nextType={nextType} crossChecks={crossChecks}/>;}else if(!review.review_complete){content=<section className={styles.complete}><strong>Sin documentos materializados para revisión</strong><span>La OT existe, pero todavía no tiene documentos vinculados al flujo de check.</span></section>;}else if(stage==="summary"){content=<ConsolidatedSummary review={review} auditors={auditors}/>;}else{content=<PriceReviewClient request={review.request} priceEvidence={review.price_lookup_evidence}/>;}
  return <main className={styles.screen}><header className={styles.header}><a className={styles.back} href="/admin-v2">← Volver a activos</a><div className={styles.topbar}><div><span className={styles.eyebrow}>CIDEF · BONOS DEALERS</span><h1>Revisión · {review.request.vin}</h1><div className={styles.meta}><span>{dealerLabel}</span><span>{review.request.estado}</span><span>{review.review_complete?"Documentos revisados":`Documento ${step} de ${sequenceDocs.length}`}</span></div></div></div></header><AuditSummary request={review.request}/><InventoryFcSummary evidence={review.fc_reconstruction}/>{review.review_complete&&!reviewingApprovedDocument&&firstDocumentHref?<p className={styles.reviewedDocsLink}><a className={styles.back} href={firstDocumentHref}>← Revisar documentos aprobados</a></p>:null}{content}</main>;
}
